# Generated by Django 5.2.7 on 2025-10-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "SuperAdmin"), (3, "User")], default=3
            ),
        ),
    ]
